apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: gateway-api
    githubRelease:
      slug: kubernetes-sigs/gateway-api
      tagSelection:
        semver:
          contraints: ">=1.2.1"
      latest: true
      assetNames:
        - standard-install.yaml
        - experimental-install.yaml
      disableAutoChecksumValidation: true
